### ISSUE TITLE
Agents hostname is set as localhost in /etc/hostname

### ISSUE THREAD

**Issue by hassaanp** [dcos-labs/dcos-gce#21]
I am trying to use contraints for certain services. I would ideally want to do that with the hostname of the nodes. But I noticed that all the agents that are spawned have localhost set as their hostname in /etc/hostname
Can someone tell me how I can change the hostnames using ansible perhaps? DCOS shows IPs for the nodes in the hostname fields.

**Comment by ajazam** [comment]
@hassaanp There is a hostname module that will allow you to change the hostname via ansible http://docs.ansible.com/ansible/latest/hostname_module.html 

I'll also modify the installation script over the weekend to add the hostname after vm creation

**Comment by ajazam** [comment]
Ignore the previous comment, I misread your comment. I'll see what I can come up with over the weekend.

**Comment by ajazam** [comment]
I've modified the installation script to add the hostname into /etc/hostname.

Unfortunately the web front end is still showing IP addresses rather than hostnames. I think you might have to use the mailing list to have your issue resolved.  

I maintain the DCOS on GCE installation scripts and documentation. I haven't used DCOS in anger yet :(

**Comment by hassaanp** [comment]
Thankyou @ajazam 
I will take this to the mailing list.
