### ISSUE TITLE
ajazam -> dcos-user

### ISSUE THREAD

**Issue by karlkfi** [dcos-labs/dcos-gce#6]
This is pretty cool!

Now that this is documented on the [dcos.io docs](https://dcos.io/docs/1.8/administration/installing/cloud/gce/), it would probably look more official if the default username was `dcos-user` or something similar, rather than `ajazam`.

**Comment by ajazam** [comment]
I wrote this for myself initially. I'm thinking of simplifying it further. Not sure how yet, but will remove ajazam from the installation procedure.

**Comment by ajazam** [comment]
Just found out that there is an official "Google Cloud Launcher template" going to be released. So that should be easier to use to create a DCOS GCE cluster. https://mesosphere.com/blog/2016/09/29/making-dcos-run-great-on-google-cloud/

I don't know anymore about it. I'm hoping that it will be more streamlined than my efforts.
